import type { Metadata } from "next";
import { Nunito_Sans as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import PageHeader from "@/components/page-header";
import "./globals.css";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Where in the world?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-screen font-sans ${fontSans.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PageHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
